<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <parent>
        <groupId>cn.iocoder.cloud</groupId>
        <artifactId>yudao</artifactId>
        <version>${revision}</version>
    </parent>
    <modelVersion>4.0.0</modelVersion>
    <modules>
        <module>telosma-module-boss-api</module>
        <module>telosma-module-boss-server</module>
    </modules>
    <artifactId>telosma-module-boss</artifactId>
    <packaging>pom</packaging>

    <name>${project.artifactId}</name>
    <description>
        boss 模块下，就是对接boss的求职工具啦
    </description>

</project>
